### ISSUE TITLE
unable to install on Mac OS X 10.9 following github instructions (Undefined symbols for architecture x86_64)

### ISSUE THREAD

**Issue by filmo** [BVLC/caffe#2868]
I've been [following these instructions](http://caffe.berkeleyvision.org/install_osx.html) and it's crashing during make. [full compile gist here](https://gist.github.com/filmo/1ea40923acc718036bdb.js)

```
CXX examples/siamese/convert_mnist_siamese_data.cpp
CXX .build_release/src/caffe/proto/caffe.pb.cc
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so
clang: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "cv::imread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      caffe::WindowDataLayer<float>::InternalThreadEntry() in window_data_layer.o
      caffe::WindowDataLayer<double>::InternalThreadEntry() in window_data_layer.o
      caffe::ReadImageToCVMat(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, bool) in io.o
  "cv::imencode(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cv::_InputArray const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >&, std::__1::vector<int, std::__1::allocator<int> > const&)", referenced from:
      caffe::ReadImageToDatum(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int, int, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, caffe::Datum*) in io.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [.build_release/lib/libcaffe.so] Error 1
make: *** Waiting for unfinished jobs....
```

I've got 
* Mac OS X 10.9.5
* XCode 6.2
* Cuda 7.5
* cuDNN for Mac (installed in /usr/local/cuda along with rest of 7.5 cuda stuff)
* Ananconda Python 2.7

I've tried every  possible version of opencv from homebrew (2.4, 3.0, kegged, compiled from scratch, opencv installed with anaconda)

I think this error has something to do with [libstdc++ versus libc++ ] (https://groups.google.com/forum/#!topic/caffe-users/G7gj03A-JPw) but don't know and don't know how to overcome it if indeed this is a problem.

This is my [most recent](https://gist.github.com/filmo/f913fd4242ba5a3b542c) Makefile.config that I tried using the anaconda opencv library. The results are the same no matter which opencv I have installed.

Any tips on getting it to work on 10.9.5?

**Comment by BlGene** [comment]
It looks like the linker is not finding OpenCV functions:
1. Try running "make VERBOSE=1" and see if the opencv path is included.
2. Try installing the normal non anaconda opencv package (if there is such a thing)

I haven't compiled anything on a Mac, so take this with a grain of salt.

BR, Max

**Comment by filmo** [comment]
Thanks for the help. I've tried the Verbose option but didn't reveal anything other than what was already indicated. I've also tried both versions of opencv available from homebrew.

**Comment by vladpopovici** [comment]
I had the same problem and managed to solve it by adding the opencv_imgcodecs library to the list in LIBRARIES variable (line 174 in the Makefile). I have the OpenCV 3.0 installed.
Best, Vlad

**Comment by ronghanghu** [comment]
This issue should have been resolved in #3186
