### ISSUE TITLE
linking error for libvorbis.so.0

### ISSUE THREAD

**Issue by giladsharir** [BVLC/caffe#757]
I'm getting the following linking errors while trying to build on Ubuntu 12.04: 

/usr/lib/x86_64-linux-gnu/libvorbis.so.0: undefined reference to `__exp_finite@GLIBC_2.15'

/usr/lib/x86_64-linux-gnu/libvorbis.so.0: undefined reference to `__acosf_finite@GLIBC_2.15'

/usr/lib/x86_64-linux-gnu/libvorbis.so.0: undefined reference to `__pow_finite@GLIBC_2.15'

/usr/lib/x86_64-linux-gnu/libvorbis.so.0: undefined reference to `__log_finite@GLIBC_2.15'

I already tried updating the libvorbis library to a newer version. 
Any suggestions to solve this issue?

Thanks

**Comment by felixlaumon** [comment]
I just encountered this issue too, and I can confirm that `mv $HOME/anaconda/lib/libm.so $HOME/anaconda/lib/libm.so.tmp` before `make all` works for me.

**Comment by jbencook** [comment]
Very helpful trick for anaconda. :+1:

**Comment by ducminhnguyen** [comment]
why do they keep making the same name that causes error, they should have their own signature name or something.

**Comment by zonca** [comment]
same issue on debian jessie and anaconda, https://github.com/BVLC/caffe/issues/757#issuecomment-72056711 fixed this.
