### ISSUE TITLE
link error at tk1

### ISSUE THREAD

**Issue by wangxingxing** [BVLC/caffe#669]
I try compile caffe on the nvidia tk1(https://developer.nvidia.com/jetson-tk1), i had compile successful on pc, but when i try compile same code at tk1 it had some link conflict. The pc and tk1 have some configure:
OS:ubuntu 14.04 
opencv 2.8.4
cuda 6.0
i haven't get a clue for this error.

/usr/bin/g++-4.6 -shared -o build/lib/libcaffe.so build/src/caffe/proto/caffe_pretty_print.pb.o build/src/caffe/proto/caffe.pb.o build/src/caffe/syncedmem.o build/src/caffe/solver.o build/src/caffe/layers/neuron_layer.o build/src/caffe/layers/accuracy_layer.o build/src/caffe/layers/image_data_layer.o build/src/caffe/layers/multinomial_logistic_loss_layer.o build/src/caffe/layers/pooling_layer.o build/src/caffe/layers/eltwise_product_layer.o build/src/caffe/layers/loss_layer.o build/src/caffe/layers/window_data_layer.o build/src/caffe/layers/hdf5_output_layer.o build/src/caffe/layers/euclidean_loss_layer.o build/src/caffe/layers/tanh_layer.o build/src/caffe/layers/dropout_layer.o build/src/caffe/layers/power_layer.o build/src/caffe/layers/relu_layer.o build/src/caffe/layers/sigmoid_layer.o build/src/caffe/layers/softmax_loss_layer.o build/src/caffe/layers/infogain_loss_layer.o build/src/caffe/layers/hdf5_data_layer.o build/src/caffe/layers/lrn_layer.o build/src/caffe/layers/memory_data_layer.o build/src/caffe/layers/inner_product_layer.o build/src/caffe/layers/conv_layer.o build/src/caffe/layers/hinge_loss_layer.o build/src/caffe/layers/im2col_layer.o build/src/caffe/layers/data_layer.o build/src/caffe/layers/concat_layer.o build/src/caffe/layers/sigmoid_cross_entropy_loss_layer.o build/src/caffe/layers/flatten_layer.o build/src/caffe/layers/softmax_layer.o build/src/caffe/layers/bnll_layer.o build/src/caffe/layers/split_layer.o build/src/caffe/net.o build/src/caffe/common.o build/src/caffe/util/upgrade_proto.o build/src/caffe/util/benchmark.o build/src/caffe/util/im2col.o build/src/caffe/util/math_functions.o build/src/caffe/util/io.o build/src/caffe/util/insert_splits.o build/src/caffe/layer_factory.o build/src/caffe/blob.o build/src/caffe/layers/pooling_layer.cuo build/src/caffe/layers/relu_layer.cuo build/src/caffe/layers/concat_layer.cuo build/src/caffe/layers/conv_layer.cuo build/src/caffe/layers/softmax_layer.cuo build/src/caffe/layers/sigmoid_layer.cuo build/src/caffe/layers/softmax_loss_layer.cuo build/src/caffe/layers/hdf5_data_layer.cuo build/src/caffe/layers/window_data_layer.cuo build/src/caffe/layers/data_layer.cuo build/src/caffe/layers/flatten_layer.cuo build/src/caffe/layers/inner_product_layer.cuo build/src/caffe/layers/eltwise_product_layer.cuo build/src/caffe/layers/image_data_layer.cuo build/src/caffe/layers/im2col_layer.cuo build/src/caffe/layers/tanh_layer.cuo build/src/caffe/layers/bnll_layer.cuo build/src/caffe/layers/dropout_layer.cuo build/src/caffe/layers/sigmoid_cross_entropy_loss_layer.cuo build/src/caffe/layers/split_layer.cuo build/src/caffe/layers/power_layer.cuo build/src/caffe/layers/lrn_layer.cuo build/src/caffe/layers/hdf5_output_layer.cuo build/src/caffe/util/math_functions.cuo build/src/caffe/util/im2col.cuo -pthread -fPIC -DNDEBUG -O2 -I/usr/local/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -Ibuild/src -I./src -I./include -I/usr/local/cuda/include -L/usr/local/lib -L/usr/local/lib -L/usr/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -lcudart -lcublas -lcurand -lpthread -lglog -lprotobuf -lleveldb -lsnappy -lboost_system -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lcblas -latlas -Wall

build/src/caffe/layers/pooling_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::PoolingLayer<float>'
build/src/caffe/layers/pooling_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/pooling_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::PoolingLayer<float>'
build/src/caffe/layers/pooling_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/pooling_layer.cuo:(.rodata+0x1c): multiple definition of `typeinfo name for caffe::PoolingLayer<double>'
build/src/caffe/layers/pooling_layer.o:(.rodata+0x1c): first defined here
build/src/caffe/layers/pooling_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::PoolingLayer<double>'
build/src/caffe/layers/pooling_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/relu_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::ReLULayer<float>'
build/src/caffe/layers/relu_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/relu_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::ReLULayer<float>'
build/src/caffe/layers/relu_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/relu_layer.cuo:(.rodata+0x18): multiple definition of `typeinfo name for caffe::ReLULayer<double>'
build/src/caffe/layers/relu_layer.o:(.rodata+0x18): first defined here
build/src/caffe/layers/relu_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::ReLULayer<double>'
build/src/caffe/layers/relu_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/concat_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::ConcatLayer<float>'
build/src/caffe/layers/concat_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/concat_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::ConcatLayer<float>'
build/src/caffe/layers/concat_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/concat_layer.cuo:(.rodata+0x1c): multiple definition of `typeinfo name for caffe::ConcatLayer<double>'
build/src/caffe/layers/concat_layer.o:(.rodata+0x1c): first defined here
build/src/caffe/layers/concat_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::ConcatLayer<double>'
build/src/caffe/layers/concat_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/conv_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::ConvolutionLayer<float>'
build/src/caffe/layers/conv_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/conv_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::ConvolutionLayer<float>'
build/src/caffe/layers/conv_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/conv_layer.cuo:(.rodata+0x20): multiple definition of `typeinfo name for caffe::ConvolutionLayer<double>'
build/src/caffe/layers/conv_layer.o:(.rodata+0x20): first defined here
build/src/caffe/layers/conv_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::ConvolutionLayer<double>'
build/src/caffe/layers/conv_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/softmax_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::SoftmaxLayer<float>'
build/src/caffe/layers/softmax_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/softmax_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::SoftmaxLayer<float>'
build/src/caffe/layers/softmax_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/softmax_layer.cuo:(.rodata+0x1c): multiple definition of `typeinfo name for caffe::SoftmaxLayer<double>'
build/src/caffe/layers/softmax_layer.o:(.rodata+0x1c): first defined here
build/src/caffe/layers/softmax_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::SoftmaxLayer<double>'
build/src/caffe/layers/softmax_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/sigmoid_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::SigmoidLayer<float>'
build/src/caffe/layers/sigmoid_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/sigmoid_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::SigmoidLayer<float>'
build/src/caffe/layers/sigmoid_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/sigmoid_layer.cuo:(.rodata+0x1c): multiple definition of `typeinfo name for caffe::SigmoidLayer<double>'
build/src/caffe/layers/sigmoid_layer.o:(.rodata+0x1c): first defined here
build/src/caffe/layers/sigmoid_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::SigmoidLayer<double>'
build/src/caffe/layers/sigmoid_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/softmax_loss_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::SoftmaxWithLossLayer<float>'
build/src/caffe/layers/softmax_loss_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/softmax_loss_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::SoftmaxWithLossLayer<float>'
build/src/caffe/layers/softmax_loss_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/softmax_loss_layer.cuo:(.rodata+0x24): multiple definition of `typeinfo name for caffe::SoftmaxWithLossLayer<double>'
build/src/caffe/layers/softmax_loss_layer.o:(.rodata+0x24): first defined here
build/src/caffe/layers/softmax_loss_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::SoftmaxWithLossLayer<double>'
build/src/caffe/layers/softmax_loss_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/hdf5_data_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::HDF5DataLayer<float>'
build/src/caffe/layers/hdf5_data_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/hdf5_data_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::HDF5DataLayer<float>'
build/src/caffe/layers/hdf5_data_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/hdf5_data_layer.cuo:(.rodata+0x1c): multiple definition of `typeinfo name for caffe::HDF5DataLayer<double>'
build/src/caffe/layers/hdf5_data_layer.o:(.rodata+0x1c): first defined here
build/src/caffe/layers/hdf5_data_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::HDF5DataLayer<double>'
build/src/caffe/layers/hdf5_data_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/window_data_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::WindowDataLayer<float>'
build/src/caffe/layers/window_data_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/window_data_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::WindowDataLayer<float>'
build/src/caffe/layers/window_data_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/window_data_layer.cuo:(.rodata+0x20): multiple definition of `typeinfo name for caffe::WindowDataLayer<double>'
build/src/caffe/layers/window_data_layer.o:(.rodata+0x20): first defined here
build/src/caffe/layers/window_data_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::WindowDataLayer<double>'
build/src/caffe/layers/window_data_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/data_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::DataLayer<float>'
build/src/caffe/layers/data_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/data_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::DataLayer<float>'
build/src/caffe/layers/data_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/data_layer.cuo:(.rodata+0x18): multiple definition of `typeinfo name for caffe::DataLayer<double>'
build/src/caffe/layers/data_layer.o:(.rodata+0x18): first defined here
build/src/caffe/layers/data_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::DataLayer<double>'
build/src/caffe/layers/data_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/flatten_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::FlattenLayer<float>'
build/src/caffe/layers/flatten_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/flatten_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::FlattenLayer<float>'
build/src/caffe/layers/flatten_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/flatten_layer.cuo:(.rodata+0x1c): multiple definition of `typeinfo name for caffe::FlattenLayer<double>'
build/src/caffe/layers/flatten_layer.o:(.rodata+0x1c): first defined here
build/src/caffe/layers/flatten_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::FlattenLayer<double>'
build/src/caffe/layers/flatten_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/inner_product_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::InnerProductLayer<float>'
build/src/caffe/layers/inner_product_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/inner_product_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::InnerProductLayer<float>'
build/src/caffe/layers/inner_product_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/inner_product_layer.cuo:(.rodata+0x20): multiple definition of `typeinfo name for caffe::InnerProductLayer<double>'
build/src/caffe/layers/inner_product_layer.o:(.rodata+0x20): first defined here
build/src/caffe/layers/inner_product_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::InnerProductLayer<double>'
build/src/caffe/layers/inner_product_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/eltwise_product_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::EltwiseProductLayer<float>'
build/src/caffe/layers/eltwise_product_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/eltwise_product_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::EltwiseProductLayer<float>'
build/src/caffe/layers/eltwise_product_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/eltwise_product_layer.cuo:(.rodata+0x24): multiple definition of `typeinfo name for caffe::EltwiseProductLayer<double>'
build/src/caffe/layers/eltwise_product_layer.o:(.rodata+0x24): first defined here
build/src/caffe/layers/eltwise_product_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::EltwiseProductLayer<double>'
build/src/caffe/layers/eltwise_product_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/image_data_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::ImageDataLayer<float>'
build/src/caffe/layers/image_data_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/image_data_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::ImageDataLayer<float>'
build/src/caffe/layers/image_data_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/image_data_layer.cuo:(.rodata+0x1c): multiple definition of `typeinfo name for caffe::ImageDataLayer<double>'
build/src/caffe/layers/image_data_layer.o:(.rodata+0x1c): first defined here
build/src/caffe/layers/image_data_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::ImageDataLayer<double>'
build/src/caffe/layers/image_data_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/im2col_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::Im2colLayer<float>'
build/src/caffe/layers/im2col_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/im2col_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::Im2colLayer<float>'
build/src/caffe/layers/im2col_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/im2col_layer.cuo:(.rodata+0x1c): multiple definition of `typeinfo name for caffe::Im2colLayer<double>'
build/src/caffe/layers/im2col_layer.o:(.rodata+0x1c): first defined here
build/src/caffe/layers/im2col_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::Im2colLayer<double>'
build/src/caffe/layers/im2col_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/tanh_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::TanHLayer<float>'
build/src/caffe/layers/tanh_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/tanh_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::TanHLayer<float>'
build/src/caffe/layers/tanh_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/tanh_layer.cuo:(.rodata+0x18): multiple definition of `typeinfo name for caffe::TanHLayer<double>'
build/src/caffe/layers/tanh_layer.o:(.rodata+0x18): first defined here
build/src/caffe/layers/tanh_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::TanHLayer<double>'
build/src/caffe/layers/tanh_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/bnll_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::BNLLLayer<float>'
build/src/caffe/layers/bnll_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/bnll_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::BNLLLayer<float>'
build/src/caffe/layers/bnll_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/bnll_layer.cuo:(.rodata+0x18): multiple definition of `typeinfo name for caffe::BNLLLayer<double>'
build/src/caffe/layers/bnll_layer.o:(.rodata+0x18): first defined here
build/src/caffe/layers/bnll_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::BNLLLayer<double>'
build/src/caffe/layers/bnll_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/dropout_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::DropoutLayer<float>'
build/src/caffe/layers/dropout_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/dropout_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::DropoutLayer<float>'
build/src/caffe/layers/dropout_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/dropout_layer.cuo:(.rodata+0x1c): multiple definition of `typeinfo name for caffe::DropoutLayer<double>'
build/src/caffe/layers/dropout_layer.o:(.rodata+0x1c): first defined here
build/src/caffe/layers/dropout_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::DropoutLayer<double>'
build/src/caffe/layers/dropout_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/sigmoid_cross_entropy_loss_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::SigmoidCrossEntropyLossLayer<float>'
build/src/caffe/layers/sigmoid_cross_entropy_loss_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/sigmoid_cross_entropy_loss_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::SigmoidCrossEntropyLossLayer<float>'
build/src/caffe/layers/sigmoid_cross_entropy_loss_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/sigmoid_cross_entropy_loss_layer.cuo:(.rodata+0x2c): multiple definition of `typeinfo name for caffe::SigmoidCrossEntropyLossLayer<double>'
build/src/caffe/layers/sigmoid_cross_entropy_loss_layer.o:(.rodata+0x2c): first defined here
build/src/caffe/layers/sigmoid_cross_entropy_loss_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::SigmoidCrossEntropyLossLayer<double>'
build/src/caffe/layers/sigmoid_cross_entropy_loss_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/split_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::SplitLayer<float>'
build/src/caffe/layers/split_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/split_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::SplitLayer<float>'
build/src/caffe/layers/split_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/split_layer.cuo:(.rodata+0x18): multiple definition of `typeinfo name for caffe::SplitLayer<double>'
build/src/caffe/layers/split_layer.o:(.rodata+0x18): first defined here
build/src/caffe/layers/split_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::SplitLayer<double>'
build/src/caffe/layers/split_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/power_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::PowerLayer<float>'
build/src/caffe/layers/power_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/power_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::PowerLayer<float>'
build/src/caffe/layers/power_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/power_layer.cuo:(.rodata+0x18): multiple definition of `typeinfo name for caffe::PowerLayer<double>'
build/src/caffe/layers/power_layer.o:(.rodata+0x18): first defined here
build/src/caffe/layers/power_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::PowerLayer<double>'
build/src/caffe/layers/power_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/lrn_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::LRNLayer<float>'
build/src/caffe/layers/lrn_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/lrn_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::LRNLayer<float>'
build/src/caffe/layers/lrn_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/lrn_layer.cuo:(.rodata+0x18): multiple definition of `typeinfo name for caffe::LRNLayer<double>'
build/src/caffe/layers/lrn_layer.o:(.rodata+0x18): first defined here
build/src/caffe/layers/lrn_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::LRNLayer<double>'
build/src/caffe/layers/lrn_layer.o:(.data.rel.ro+0xc): first defined here
build/src/caffe/layers/hdf5_output_layer.cuo:(.rodata+0x0): multiple definition of `typeinfo name for caffe::HDF5OutputLayer<float>'
build/src/caffe/layers/hdf5_output_layer.o:(.rodata+0x0): first defined here
build/src/caffe/layers/hdf5_output_layer.cuo:(.data.rel.ro+0x0): multiple definition of`typeinfo for caffe::HDF5OutputLayer<float>'
build/src/caffe/layers/hdf5_output_layer.o:(.data.rel.ro+0x0): first defined here
build/src/caffe/layers/hdf5_output_layer.cuo:(.rodata+0x20): multiple definition of `typeinfo name for caffe::HDF5OutputLayer<double>'
build/src/caffe/layers/hdf5_output_layer.o:(.rodata+0x20): first defined here
build/src/caffe/layers/hdf5_output_layer.cuo:(.data.rel.ro+0xc): multiple definition of`typeinfo for caffe::HDF5OutputLayer<double>'
build/src/caffe/layers/hdf5_output_layer.o:(.data.rel.ro+0xc): first defined here
collect2: ld returned 1 exit status
make: **\* [build/lib/libcaffe.so] Error 1

**Comment by huangshiyou** [comment]
Ah it works with the method provided by @wangxingxing  & @carlodelmundo . Thanks

**Comment by ildoonet** [comment]
I got working with g++ 4.7 version on tk1 board

sed -i "s/# CUSTOM_CXX := g++/CUSTOM_CXX := g++-4.7/" Makefile.config
