### ISSUE TITLE
Matlab libcaffe "undefined symbol" error

### ISSUE THREAD

**Issue by ericbarnhill** [BVLC/caffe#4317]
Hi, caffe compiles fine, and VSRnet demo almost runs. I get this error:

Invalid MEX-file '/home/ericbarnhill/Documents/code/caffe-master/matlab/+caffe/private/caffe_.mexa64':
/home/ericbarnhill/Documents/code/caffe-master/matlab/+caffe/private/libcaffe.so.1.0.0-rc3: undefined symbol:
_ZN2cv8imencodeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_11_InputArrayERSt6vectorIhSaIhEERKSB_IiSaIiEE

Could this relate to a clash of C++ versions? 

Note that I have to set the correct c++ version to run caffe in Matlab by setting LD_PRELOAD. It does run however, until this point. Could this be related to c++ versioning and my need to rely on LD_PRELOAD?

Thanks for any support!

**Comment by ericbarnhill** [comment]
Update: 

Re-compiling caffe appeared to require building protobuf with 4.7 which I did.

However then I get the error, compiling 

/home/ericbarnhill/Documents/code/caffe-master/build/include/caffe/proto/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
/home/ericbarnhill/Documents/code/caffe-master/build/include/caffe/proto/caffe.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
/home/ericbarnhill/Documents/code/caffe-master/build/include/caffe/proto/caffe.pb.h:14:2: error: #error your headers.

I am unsure what is meant by "this file" and wondering if anyone can spare a moment to suggest whether 

a) caffe cannot be built with 4.7 at this point, which is what this error message appears to suggest
b) caffe can be build with 4.7, this problem is probably an issue with how I built protobuf
c) caffe cannot be built with 4.7 but we are able to use it successfully with Matlab 2015+ without VSRnet dumping core

Much thanks for any help!

**Comment by harshal2802** [comment]
i think this maybe related to protoc version 2.5 then " #error This file was generated by a newer version of protoc which is" will go further for next compilation
