### ISSUE TITLE
CUDA version required for multi-GPU

### ISSUE THREAD

**Issue by lukeyeager** [BVLC/caffe#2954]
The Installation instructions claim that CUDA >=5.0 is supported.

> CUDA is required for GPU mode.
>   library version 7.0 and the latest driver version are recommended, but 6.\* is fine too
>   5.5, and 5.0 are compatible but considered legacy
> https://github.com/BVLC/caffe/blob/6232233e44/docs/installation.md#prerequisites

It seems unclear to me whether Caffe claims to support compute capability <3.0 or not.

> We have not encountered any trouble in-house with devices with CUDA capability >= 3.0.
> ...
> devices with compute capability <= 2.0 may have to reduce CUDA thread numbers and batch sizes due to hardware constraints. Your mileage may vary.
> https://github.com/BVLC/caffe/blob/6232233e44/docs/installation.md#hardware

But it appears that #2903 doesn't work with CUDA <7.0 and/or compute capability <3.0 _(NOTE - technically this was NVIDIA/caffe, but the multi-GPU code is essentially the same)_.

> The problem was in Cuda, in our cluster we had Cuda 6.5 after updating to Cuda 7.0 everything worked as it's supposed to be, even on compute capabilities 2.0
> https://groups.google.com/d/msg/digits-users/CXhe4_W9Dyo/sIjjr2KZJAAJ

See also:

> I tried to compile a new version of caffe and ran into this error: 'struct cudaDeviceProp' has no member named 'isMultiGpuBoard  . I guess it is because a new prerequisite is needed for multi-gpu support. 
> https://groups.google.com/d/msg/caffe-users/md4X0Y8WKZ0/ri0_HThxDQAJ

It seems to me that either the documentation needs to change, or the code needs to be made more compatible with older CUDA/GPUs.

**Comment by thatguymike** [comment]
isMultiGpuBoard has been available since CUDA 6.0.  We can look at ifdef'ing for earlier runtimes, but 6.0 is pretty old release wise already and so much of the new work is CUDA 6.5 or newer required really.

**Comment by longjon** [comment]
I've never heard great reasons for supporting older versions of CUDA, so I'm in favor of upping the stated requirements and simplifying code where possible.

**Comment by ToxidoLiu** [comment]
I used `sudo apt-get install Nvidia-cuda-toolkit` and then modified the **Makefile.config** correspondingly by uncommenting `CUDA_DIR := /usr `, the same error occurred. I use `nvcc -V` command to check for the CUDA version and it was 5.5. So I assume its the compatibility issue because I used the online package on NVIDIA website and the build was successful.

**Comment by cypof** [comment]
Multi-GPU is now based on NCCL, which requires at least CUDA 7.0.
