### ISSUE TITLE
Draw Net Problem

### ISSUE THREAD

**Issue by BestSonny** [BVLC/caffe#1709]
I try to visualize the network.But I get the errors.

#########################
AttributeError: type object 'LayerParameter' has no attribute 'LayerType'
#########################

I check the caffe caffe_pb2.py  and get this:
#########################
_LAYERPARAMETER_LAYERTYPE = descriptor.EnumDescriptor(
  name='LayerType',
  full_name='caffe.LayerParameter.LayerType',
  filename=None,
  file=DESCRIPTOR,
#########################

Below is my use case:
#########################
import caffe
from caffe import draw
from caffe.proto import caffe_pb2

#enddef
net =  caffe_pb2.NetParameter()
with open('model/_iter_500000.caffemodel','rb') as f:
    net.ParseFromString(f.read())
print net.name
draw.draw_net_to_file(net,'network.png')
#########################

**Comment by shelhamer** [comment]
Do `./python/draw_net.py net.prototxt visualization.png`. Please ask usage questions on the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) mailing list.

**Comment by jsupancic** [comment]
Hi,

This is a real bug (on the dev branch at least) and should be corrected. The problem is that you updated the layers protobuf format without updating draw_net.py

I've uploaded a patch here:
http://www.ics.uci.edu/~jsupanci/draw.patch

Best,
James Supancic III
PhD Candidate - University of California, Irvine

**Comment by shelhamer** [comment]
@jsupancic can you send a PR to dev with the fix? This was broken by #1694. Thanks.

**Comment by jsupancic** [comment]
@shelhamer I've sent a PR to Dev with the fix (https://github.com/BVLC/caffe/pull/1860)

Best,
James

**Comment by yashchitalia** [comment]
Hey @jsupancic , thanks for the patch! I implemented it manually in my draw.py, and am getting the following error: 
```
File "/home/user/3rdparty/caffe/python/caffe/draw.py", line 25, in get_pydot_graph
    for layer in caffe_net.layer:
AttributeError: 'NetParameter' object has no attribute 'layer'
```
Any ideas?

**Comment by jsupancic** [comment]
Dear Yash,

My guess is a syntax error/version mismatch in your net.prototxt file.
Could you send me (1) the command you are running and (2) the network
prototxt you are trying with?

Best,
James
​

**Comment by nastyad** [comment]
Dear James and Evan,

I downloaded and compiled the latest versions of both master and dev branches, but I still get the error
AttributeError: type object 'PoolingParameter' has no attribute 'PoolMethod'

I run the command (from Caffe installation directory)
./python/draw_net.py ./examples/cifar10/cifar10_quick_train_test.prototxt ./visualization.png

Do you have any idea why this may happen?

Thank you in advance,
Anastasia

**Comment by jsupancic** [comment]
Dear Anastasia  @nastyad ,
 
I cannot reproduce your problem. When I 
(1) cloned a clean copy of caffe
(2) mkdir build, cd build, make -j16, cd .. 
(3)  ./python/draw_net.py ./examples/cifar10/cifar10_quick_train_test.prototxt ./visualization.png  
no errors occur. 

My *guess* is that something is wrong with the Python implementation of the caffe protobufs, maybe due to some version incompatibility?  Could you post your caffe_pb2.py somewhere? 

Best,
James

**Comment by nastyad** [comment]
Dear James,

I put the file here: http://www.cs.technion.ac.il/~nastyad/caffe_pb2.py

Thanks,
Anastasia

**Comment by b2220333** [comment]
Hello, I try to git pull to the latest caffe code ,and make all; make pycaffe;
After that I still have the same problem:
sam@sam:~/code/download/CNN/caffe/caffe$ ./python/draw_net.py models/bvlc_reference_caffenet/deploy.prototxt ./abc.png
Drawing net to ./abc.png
Traceback (most recent call last):
  File "./python/draw_net.py", line 44, in <module>
    main()
  File "./python/draw_net.py", line 40, in main
    caffe.draw.draw_net_to_file(net, args.output_image_file, args.rankdir)
  File "/home/sam/code/download/CNN/caffe/caffe/python/caffe/draw.py", line 172, in draw_net_to_file
    fid.write(draw_net(caffe_net, rankdir, ext))
  File "/home/sam/code/download/CNN/caffe/caffe/python/caffe/draw.py", line 162, in draw_net
    return get_pydot_graph(caffe_net, rankdir).create(format=ext)
  File "/home/sam/code/download/CNN/caffe/caffe/python/caffe/draw.py", line 115, in get_pydot_graph
    node_label = determine_node_label_by_layertype(layer, layertype, rankdir)
  File "/home/sam/code/download/CNN/caffe/caffe/python/caffe/draw.py", line 78, in determine_node_label_by_layertype
    pooling_types_dict = get_pooling_types_dict()
  File "/home/sam/code/download/CNN/caffe/caffe/python/caffe/draw.py", line 28, in get_pooling_types_dict
    desc = caffe_pb2.PoolingParameter.PoolMethod.DESCRIPTOR
AttributeError: type object 'PoolingParameter' has no attribute 'PoolMethod'
sam@sam:~/code/download/CNN/caffe/caffe$ 

How to fix it?
Thank you~

**Comment by VPlatoon** [comment]
Try to build the latest protobuf, install it in /usr, compile python wrapper too. And re-build Caffe again.

**Comment by howtobeahacker** [comment]
@VPlatoon Hi, do you solve the problem by installing the latest protobuf? Thank you.
