### ISSUE TITLE
Compile fails using g++ 4.8 & g++ 4.6

### ISSUE THREAD

**Issue by Jack-Foster** [BVLC/caffe#3301]
I have a similar issue than this one : https://github.com/BVLC/caffe/issues/337 
That is build fails with g++ 4.8 with   error message "kernel launches from templates are not allowed in system files".

A solution to this issue is to use g++4.6 but it does not work in my case because caffe now requests some new includes that do not exist for g++4.6.
 For instance in .build_release/src/caffe/proto/caffe.pb.h line 7 looks after string include :
 #include <string>

This include exists with g++-4.8 but doesn't with g++-4.6.... 
 I  tried to install this include (from g++-4.8) and compile with g++-4.6 but it (obviously) gives weird errors : 

In file included from /usr/include/c++/4.8/bits/basic_string.h:39:0,
 from /usr/include/c++/4.8/string:52,
 from /usr/include/google/protobuf/stubs/common.h:41,
 from .build_release/src/caffe/proto/caffe.pb.h:9,
 from .build_release/src/caffe/proto/caffe.pb.cc:5:
 /usr/include/c++/4.8/ext/atomicity.h: In function ‘_Atomic_word __gnu_cxx::__exchange_and_add(volatile _Atomic_word, int)’:
 /usr/include/c++/4.8/ext/atomicity.h:49:45: error: ‘__ATOMIC_ACQ_REL’ was not declared in this scope
 /usr/include/c++/4.8/ext/atomicity.h:49:61: error: ‘__atomic_fetch_add’ was not declared in this scope
 /usr/include/c++/4.8/ext/atomicity.h: In function ‘void __gnu_cxx::__atomic_add(volatile _Atomic_word, int)’:
 /usr/include/c++/4.8/ext/atomicity.h:53:38: error: ‘__ATOMIC_ACQ_REL’ was not declared in this scope
 /usr/include/c++/4.8/ext/atomicity.h:53:54: error: ‘__atomic_fetch_add’ was not declared in this scope
 Makefile:551: recipe for target '.build_release/src/caffe/proto/caffe.pb.o' failed

Could anyone give me some help on this ? Thx

**Comment by ronghanghu** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues.
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
