### ISSUE TITLE
Building MATLAB wrapper "__OSX_AVAILABLE_BUT_DEPRECATED"

### ISSUE THREAD

**Issue by damro** [BVLC/caffe#915]
Hey there!
I hope someone can help me with this issue. When compiling the MATLAB wrapper with 'make matcaffe' I get the following error.

Building with 'Xcode Clang++'.
In file included from /Users/damian/workspace/caffe/matlab/caffe/matcaffe.cpp:12:
In file included from ./include/caffe/caffe.hpp:8:
In file included from ./include/caffe/blob.hpp:8:
In file included from ./include/caffe/syncedmem.hpp:9:
In file included from ./include/caffe/util/math_functions.hpp:12:
In file included from ./include/caffe/util/mkl_alternate.hpp:13:
/System/Library/Frameworks/vecLib.framework/Versions/Current/Headers/cblas.h:640:40: error: expected function body after function declarator
extern void ATLU_DestroyThreadMemory() __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_2, __MAC_10_9, __IPHONE_4_0, __IPHONE_NA);
                                       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/Availability.h:155:53: note: expanded from macro '__OSX_AVAILABLE_BUT_DEPRECATED'
                                                    __AVAILABILITY_INTERNAL##_osxIntro##_DEP##_osxDep
                                                    ^
<scratch space>:106:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_2_DEP__MAC_10_9
^
1 error generated.

make: **\* [matlab/caffe/caffe.mexmaci64] Error 255

The MATLAB version 2014a and I'm trying to get it working on a MAC OSX 10.9. I'm already on the dev branch using the fix provided in the previous issues with MATLAB 2014a but this didn't solve it.
Does anybody has an idea how to fix this issue?

Thank you for your help!

**Comment by AlamiMejjati** [comment]
Hi there i'm having a problem when trying to tape: make matcaffe on a shell. 
i'm getting this error message: 
MEX matlab/+caffe/private/caffe_.cpp
Building with 'Xcode Clang++'.
In file included from /Users/MBP/caffe/matlab/+caffe/private/caffe_.cpp:18:
In file included from ./include/caffe/caffe.hpp:7:
In file included from ./include/caffe/blob.hpp:10:
In file included from ./include/caffe/syncedmem.hpp:7:
In file included from ./include/caffe/util/math_functions.hpp:11:
In file included from ./include/caffe/util/mkl_alternate.hpp:11:
/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Headers/cblas.h:760:26: error: expected function body after function declarator
        const int __ldc) __OSX_AVAILABLE_STARTING(__MAC_10_10,__IPHONE_8_0);
                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/Availability.h:159:50: note: expanded from macro '__OSX_AVAILABLE_STARTING'
    #define __OSX_AVAILABLE_STARTING(_osx, _ios) __AVAILABILITY_INTERNAL##_osx
                                                 ^
<scratch space>:6:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_10
^
In file included from /Users/MBP/caffe/matlab/+caffe/private/caffe_.cpp:18:
In file included from ./include/caffe/caffe.hpp:7:
In file included from ./include/caffe/blob.hpp:10:
In file included from ./include/caffe/syncedmem.hpp:7:
In file included from ./include/caffe/util/math_functions.hpp:11:
In file included from ./include/caffe/util/mkl_alternate.hpp:11:
/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Headers/cblas.h:767:26: error: expected function body after function declarator
        const int __ldc) __OSX_AVAILABLE_STARTING(__MAC_10_10,__IPHONE_8_0);
                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/Availability.h:159:50: note: expanded from macro '__OSX_AVAILABLE_STARTING'
    #define __OSX_AVAILABLE_STARTING(_osx, _ios) __AVAILABILITY_INTERNAL##_osx
                                                 ^
<scratch space>:6:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_10
^
2 errors generated.

make: *** [matlab/+caffe/private/caffe_.mexmaci64] Error 255
 

i tried to change the blas.h file like @drdan14  said but i only have the lecture rights. 
@vimalthilak  @damro  @drdan14  @shelhamer  you guys have some ideas to help me ?

**Comment by NRmf** [comment]
@AlamiMejjati I am having the same error. 
Did you manage to fix it?

**Comment by alihassan1** [comment]
@NRmf I'm have the exact same issue with similar configuration (OSX Yosemite 10.11, Matlab_R2015b). 
were you able to fix it?

**Comment by AlamiMejjati** [comment]
Sorry guys, my solution was to move on ubuntu. It is way easier to install. Goog luck ;)

**Comment by yiisama** [comment]
same error, many symbol(s) not found for architecture x86_64

one is cv::String::(de)allocate, others are google::protobuf::xxxxxx......

Every possible solution mentioned above have been tried but still.....

DESPERATE, please help if you have any idea...

**Comment by yiisama** [comment]
Problems solved thanks to https://groups.google.com/forum/#!topic/caffe-users/BZgh3mtaR2o

Just remember to make clean & make all before make matcaffe.

Anyway homebrew helps a lot in version control.

**Comment by emojiface-ops** [comment]
Being driven mad by the "Undefined symbols for architecture x86_64:  _mxArrayToString" issue. Have read this thread half a dozen times and still can't seem to fix it. I'm using Matlab 2017a on OS X Sierra 10.12.5, Xcode 8.3.3.

I've tried:

- Replacing existing LIBRARY_DIRS with "LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib $(MATLAB_DIR)/bin/maci64 /usr/lib"; also tried moving "maci64" before "/usr/local/lib"
- Search/replace in mexopts.sh "10.8" with "10.12"
- Search/replace in mexopts.sh "-lc++" with "-lstdc++"
- Running "mex -setup" in Matlab
- "Make clean" then "Make matcaffe"

Still getting the error. Help! :)

**Comment by yizhichun** [comment]
@emojiface-ops 
I have encountered the same problem, i need help

**Comment by LiangChaoPossible** [comment]
@emojiface-ops
I've tried as same as you did , but still find the

Undefined symbols for architecture x86_64:
  "_mxArrayToString", referenced from:
      get_solver(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      solver_restore(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      get_net(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      net_copy_from(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      net_save(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      read_mean(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      write_mean(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o

do you fix that ?
