### ISSUE TITLE
Installation instructions should list minimum version of gflags

### ISSUE THREAD

**Issue by prehensilecode** [BVLC/caffe#5741]
### Issue summary
[Installation instructions](http://caffe.berkeleyvision.org/installation.html) do not specify minimum version of gflags (nor of a few other prerequisites).  Trying to compile using gflags 1.3 gives this error:

```
tools/caffe.cpp: In function ‘int main(int, char**)’:
tools/caffe.cpp:433:3: error: ‘SetVersionString’ is not a member of ‘gflags’
   gflags::SetVersionString(AS_STRING(CAFFE_VERSION));
```

Looking through the gflags history, it looks like this was introduced in 1.6.

### Steps to reproduce
Edit Makefile.config appropriately, then do: "make clean ; make"

### Your system configuration
Operating system: Red Hat Enterprise Linux 6.5
Compiler: gcc 4.8.1
CUDA version (if applicable): n/a
CUDNN version (if applicable): n/a
BLAS: openblas
Python or MATLAB version (for pycaffe and matcaffe respectively): Python 2.7.13
gflags version: 1.3 (via EPEL)
