### ISSUE TITLE
error: when build tools/extract_features.bin

### ISSUE THREAD

**Issue by mender05** [BVLC/caffe#985]
## I get following errors while trying to build on Ubuntu 14.04: 

g++ tools/extract_features.cpp -pthread -fPIC -DNDEBUG -O2 -I/usr/include/python2.7 -I/usr   /lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/usr/local/cuda/include -Wall -Wno-sign-compare -c -o .build_release/tools/extract_features.o 2> .build_release/tools/extract_features.o.warnings.txt \
                || (cat .build_release/tools/extract_features.o.warnings.txt; exit 1)

g++ .build_release/tools/extract_features.o .build_release/lib/libcaffe.a -o .build_release/tools/extract_features.bin -fPIC -DNDEBUG -O2 -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/usr/local/cuda/include -Wall -Wno-sign-compare -L/home/mender/anaconda/lib -L/usr/local/lib -L/usr/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -lcudart -lcublas -lcurand -lglog -lgflags -lpthread -lprotobuf -lleveldb -lsnappy -llmdb -lboost_system -lhdf5_hl -lhdf5 -lopencv_core -lopencv_highgui -lopencv_imgproc -lcblas -latlas

//usr/lib/x86_64-linux-gnu/libx264.so.142: undefined reference to `__exp_finite@GLIBC_2.15'
//usr/lib/x86_64-linux-gnu/libx264.so.142: undefined reference to`__log10_finite@GLIBC_2.15'
//usr/lib/x86_64-linux-gnu/libxvidcore.so.4: undefined reference to `__logf_finite@GLIBC_2.15'
//usr/lib/x86_64-linux-gnu/libvorbis.so.0: undefined reference to`__acosf_finite@GLIBC_2.15'
//usr/lib/x86_64-linux-gnu/libx264.so.142: undefined reference to `__pow_finite@GLIBC_2.15'
//usr/lib/x86_64-linux-gnu/libx264.so.142: undefined reference to`__log2_finite@GLIBC_2.15'
//usr/lib/x86_64-linux-gnu/libxvidcore.so.4: undefined reference to `__log10f_finite@GLIBC_2.15'
//usr/lib/x86_64-linux-gnu/libxvidcore.so.4: undefined reference to`__log_finite@GLIBC_2.15'
//usr/lib/x86_64-linux-gnu/libx264.so.142: undefined reference to `__powf_finite@GLIBC_2.15'
//usr/lib/x86_64-linux-gnu/libx264.so.142: undefined reference to`__log2f_finite@GLIBC_2.15'
collect2: ld returned 1 exit status
make: **\* [.build_release/tools/extract_features.bin] Error 1
## My Makefile.config setting likes this:

CUDA_DIR := /usr/local/cuda
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
                -gencode arch=compute_20,code=sm_21 \
                -gencode arch=compute_30,code=sm_30 \
                -gencode arch=compute_35,code=sm_35 \
                -gencode arch=compute_50,code=sm_50 \
                -gencode arch=compute_50,code=compute_50
BLAS := atlas
MATLAB_DIR := /usr/local/MATLAB/R2012b
PYTHON_INCLUDE := $(HOME)/anaconda/include \
                  $(HOME)/anaconda/include/python2.7 \
                  $(HOME)/anaconda/lib/python2.7/site-packages/numpy/core/include
PYTHON_LIB := $(HOME)/anaconda/lib
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib
BUILD_DIR := build
DISTRIBUTE_DIR := distribute
TEST_GPUID := 0
## g++ --version

g++ (Ubuntu/Linaro 4.6.4-6ubuntu2) 4.6.4
## echo $LD_LIBRARY_PATH

/home/anaconda/lib:/usr/local/cuda-6.0/lib64:/usr/local/lib:/usr/lib:

This problem seems like #757, but I don't know how to get ride of the error. Where things go wrong?
Thanks.

**Comment by as133** [comment]
Fixed my problem too. 

+1 for adding to installation page.

**Comment by XucongZhang** [comment]
fixed my problem too!

**Comment by prasttika** [comment]
also fixed my problem by commenting the PYTHON_LIB  in Makefile.config - thanks

**Comment by zeeshanhaider1007** [comment]
I am facing same sort of error while installing caffe with Anaconda.

- [ 82%] Linking CXX executable extract_features
- CMakeFiles/extract_features.dir/extract_features.cpp.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<int, int>(int const&, int const&, char const*)':
- extract_features.cpp:(.text._ZN6google17MakeCheckOpStringIiiEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiiEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc]+0x50): undefined reference to `google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()'
- CMakeFiles/extract_features.dir/extract_features.cpp.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* google::MakeCheckOpString<unsigned long, unsigned long>(unsigned long const&, unsigned long const&, char const*)':
- extract_features.cpp:(.text._ZN6google17MakeCheckOpStringImmEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc[_ZN6google17MakeCheckOpStringImmEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_RKT0_PKc]+0x51): undefined reference to `google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()'
- ../lib/libcaffe.so.1.0.0: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
- ../lib/libcaffe.so.1.0.0: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
- collect2: error: ld returned 1 exit status
- tools/CMakeFiles/extract_features.dir/build.make:129: recipe for target 'tools/extract_features' failed
- make[2]: *** [tools/extract_features] Error 1
- CMakeFiles/Makefile2:457: recipe for target 'tools/CMakeFiles/extract_features.dir/all' failed
- make[1]: *** [tools/CMakeFiles/extract_features.dir/all] Error 2
- Makefile:127: recipe for target 'all' failed
- make: *** [all] Error 2

- Makefile.config which I updated looks like this
`## Refer to http://caffe.berkeleyvision.org/installation.html
# Contributions simplifying and improving our build system are welcome!

# cuDNN acceleration switch (uncomment to build with cuDNN).
# USE_CUDNN := 1

# CPU-only switch (uncomment to build without GPU support).
 CPU_ONLY := 1

# uncomment to disable IO dependencies and corresponding data layers
# USE_OPENCV := 0
 USE_LEVELDB := 0
# USE_LMDB := 0

# uncomment to allow MDB_NOLOCK when reading LMDB files (only if necessary)
#	You should not set this flag if you will be reading LMDBs with any
#	possibility of simultaneous read and write
# ALLOW_LMDB_NOLOCK := 1

# Uncomment if you're using OpenCV 3
 #OPENCV_VERSION := 3

# To customize your choice of compiler, uncomment and set the following.
# N.B. the default for Linux is g++ and the default for OSX is clang++
# CUSTOM_CXX := g++

# CUDA directory contains bin/ and lib/ directories that we need.
#CUDA_DIR := /usr/local/cuda
# On Ubuntu 14.04, if cuda tools are installed via
# "sudo apt-get install nvidia-cuda-toolkit" then use this instead:
# CUDA_DIR := /usr

# CUDA architecture setting: going with all of them.
# For CUDA < 6.0, comment the *_50 through *_61 lines for compatibility.
# For CUDA < 8.0, comment the *_60 and *_61 lines for compatibility.
# For CUDA >= 9.0, comment the *_20 and *_21 lines for compatibility.
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
		-gencode arch=compute_20,code=sm_21 \
		-gencode arch=compute_30,code=sm_30 \
		-gencode arch=compute_35,code=sm_35 \
		-gencode arch=compute_50,code=sm_50 \
		-gencode arch=compute_52,code=sm_52 \
		-gencode arch=compute_60,code=sm_60 \
		-gencode arch=compute_61,code=sm_61 \
		-gencode arch=compute_61,code=compute_61

# BLAS choice:
# atlas for ATLAS (default)
# mkl for MKL
# open for OpenBlas
#BLAS := atlas
# Custom (MKL/ATLAS/OpenBLAS) include and lib directories.
# Leave commented to accept the defaults for your choice of BLAS
# (which should work)!
# BLAS_INCLUDE := /path/to/your/blas
# BLAS_LIB := /path/to/your/blas

# Homebrew puts openblas in a directory that is not on the standard search path
# BLAS_INCLUDE := $(shell brew --prefix openblas)/include
# BLAS_LIB := $(shell brew --prefix openblas)/lib

# This is required only if you will compile the matlab interface.
# MATLAB directory should contain the mex binary in /bin.
# MATLAB_DIR := /usr/local
# MATLAB_DIR := /Applications/MATLAB_R2012b.app

# NOTE: this is required only if you will compile the python interface.
# We need to be able to find Python.h and numpy/arrayobject.h.
#PYTHON_INCLUDE := /usr/include/python2.7 \
#		/usr/lib/python2.7/dist-packages/numpy/core/include
# Anaconda Python distribution is quite popular. Include path:
# Verify anaconda location, sometimes it's in root.
 ANACONDA_HOME := $(HOME)/anaconda2
 PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
		 $(ANACONDA_HOME)/include/python2.7 \
		 $(ANACONDA_HOME)/lib/python2.7/site-packages/numpy/core/include

# Uncomment to use Python 3 (default is Python 2)
# PYTHON_LIBRARIES := boost_python3 python3.5m
# PYTHON_INCLUDE := /usr/include/python3.5m \
#                 /usr/lib/python3.5/dist-packages/numpy/core/include

# We need to be able to find libpythonX.X.so or .dylib.
#PYTHON_LIB := /usr/lib
 PYTHON_LIB := $(ANACONDA_HOME)/lib

# Homebrew installs numpy in a non standard path (keg only)
# PYTHON_INCLUDE += $(dir $(shell python -c 'import numpy.core; print(numpy.core.__file__)'))/include
# PYTHON_LIB += $(shell brew --prefix numpy)/lib

# Uncomment to support layers written in Python (will link against Python libs)
 WITH_PYTHON_LAYER := 1

# Whatever else you find you need goes here.
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib

# If Homebrew is installed at a non standard location (for example your home directory) and you use it for general dependencies
# INCLUDE_DIRS += $(shell brew --prefix)/include
# LIBRARY_DIRS += $(shell brew --prefix)/lib

# NCCL acceleration switch (uncomment to build with NCCL)
# https://github.com/NVIDIA/nccl (last tested version: v1.2.3-1+cuda8.0)
# USE_NCCL := 1

# Uncomment to use `pkg-config` to specify OpenCV library paths.
# (Usually not necessary -- OpenCV libraries are normally installed in one of the above $LIBRARY_DIRS.)
# USE_PKG_CONFIG := 1

# N.B. both build and distribute dirs are cleared on `make clean`
BUILD_DIR := build
DISTRIBUTE_DIR := distribute

# Uncomment for debugging. Does not work on OSX due to https://github.com/BVLC/caffe/issues/171
# DEBUG := 1

# The ID of the GPU that 'make runtest' will use to run unit tests.
TEST_GPUID := 0

# enable pretty build (comment to see full commands)
Q ?= @`
