### ISSUE TITLE
cannot compile on Centos 6.7

### ISSUE THREAD

**Issue by enixonumm** [BVLC/caffe#3686]
Hello, I am trying to compile caffe with a CPU only installation on Centos 6.7.
I have boost version  boost-1.41.0-27.el6.x86_64
I tried looking for a newer version of boost but none seem to be available for Centos 6.7.
When I run make all, I receive the following error message.
Any suggestions for what might be causing this and/or how to fix it?

##INPUT
make all

####OUTPUT
CXX src/caffe/parallel.cpp
In file included from ./include/caffe/caffe.hpp:18,
                 from src/caffe/parallel.cpp:12:
./include/caffe/util/io.hpp: In function 'void caffe::MakeTempDir(std::string*)':
./include/caffe/util/io.hpp:27: error: 'temp_directory_path' is not a member of 'boost::filesystem'
./include/caffe/util/io.hpp:29: error: 'unique_path' is not a member of 'boost::filesystem'
make: *** [.build_release/src/caffe/parallel.o] Error 1

**Comment by seanbell** [comment]
You could try using docker (https://github.com/BVLC/caffe/pull/3518) which allows you to use Ubuntu.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by enixonumm** [comment]
Thanks.
I just downloaded the docker but I am not sure if I can get it to work as
is on Centos 6.7.
There is not an apt-get repository for centos 6.7.
I will probably try to rewrite parts of the docker file to make it
compatible.

-Erika



Erika Nixon
Data Analyst
University of Maryland Baltimore

410-706-3311
enixon.umm@gmail.com
enixon@umm.edu

-
This e-mail and any accompanying attachments may be privileged,
confidential, contain protected health information about an identified patient
or be otherwise protected from disclosure. State and federal law
protect the confidentiality
of this information. If the reader of this message is not the intended
recipient;
you are prohibited from using, disclosing, reproducing or distributing
this information;
you should immediately notify the sender by telephone or e-mail and
delete this e-mail.

**Comment by elezar** [comment]
@enixonumm The docker file should be self-contained, and does not depend on what your host OS is (for most purposes). If you don't have docker installed, consider looking at the instructions at https://docs.docker.com/engine/installation/linux/centos/

You should then be able to build the docker images if you fetch the relevant pull request (or create your own docker images using those as a basis).

**Comment by enixonumm** [comment]
Thanks!
It works!
-Erika


Erika Nixon
Data Analyst
University of Maryland Baltimore

410-706-3311
enixon.umm@gmail.com
enixon@umm.edu

-
This e-mail and any accompanying attachments may be privileged,
confidential, contain protected health information about an identified patient
or be otherwise protected from disclosure. State and federal law
protect the confidentiality
of this information. If the reader of this message is not the intended
recipient;
you are prohibited from using, disclosing, reproducing or distributing
this information;
you should immediately notify the sender by telephone or e-mail and
delete this e-mail.

**Comment by SevenGong** [comment]
@enixonumm I get the problems as yours, Is installing docker the only way to solve this ?

**Comment by yunchih** [comment]
@elezar @SevenGong  I get the same problems.  Any idea? 
Thanks

**Comment by enixonumm** [comment]
Hi, using the docker image only worked briefly for me.
It quickly filled up my root directory and I had to expunge it from my
system to get the system to work again.
If you are going to use the docker make sure that you have plenty of space
in your root directory.
If not, you would have to repartition your hard drives which I was not
willing to do.
My ultimate solution was to put ubuntu on an old computer that wasn't been
used.

Good luck!

-Erika



Erika Nixon
Data Analyst
University of Maryland Baltimore

410-706-3311
enixon.umm@gmail.com
enixon@umm.edu

-
This e-mail and any accompanying attachments may be privileged,
confidential, contain protected health information about an identified patient
or be otherwise protected from disclosure. State and federal law
protect the confidentiality
of this information. If the reader of this message is not the intended
recipient;
you are prohibited from using, disclosing, reproducing or distributing
this information;
you should immediately notify the sender by telephone or e-mail and
delete this e-mail.

**Comment by HolmesShuan** [comment]
@SevenGong @yunchih I solved this problem by installing [boost_1.60 ](http://www.boost.org/)or you may have to install [caffe-rc2](https://github.com/BVLC/caffe/releases) instead. 
Makefile.config @ line 65/66:
`# Whatever else you find you need goes here.
INCLUDE_DIRS := $(PYTHON_INCLUDE) /home/xxx/boost/include /usr/local/include
LIBRARY_DIRS := $(PYTHON_LIB) /home/xxx/boost/lib /usr/local/lib /usr/lib /usr/lib64 /usr/lib64/atlas /usr/local/cuda/lib64`
Following steps to install boost:
`./bootstrap.sh --prefix=path/to/installation/prefix`
`./b2 install`
