### ISSUE TITLE
Solve the problem: "cannot find -lboost_python3" when using Python3 Ubuntu16.04

### ISSUE THREAD

**Issue by H-adorable** [BVLC/caffe#4843]
When 

```
make all
```

> cannot find -lboost_python3

occurred.

Then I went to 

> /usr/lib/x86_64-linux-gnu

search and found that the library file is in different name as

> libboost_python-py35.so

so I made a link by following command

``` bash
sudo ln -s libboost_python-py35.so libboost_python3.so 
```

which solved my problem.

Suggest that this step could add to **Installation Guide**

**Comment by supernovaremnant** [comment]
solved my problem thx !

**Comment by MarcosPieras** [comment]
Hi, I am in similar situation, which version of python and libboost did you use ?
thanks

**Comment by varunagrawal** [comment]
This solution did not work for me, unfortunately. Any reason why?
I changed the `boost_python3` in the Makefile.config to `boost_python3-py35` and it worked perfectly.

**Comment by MarcosPieras** [comment]
I solved using cmake. I modified the cmakelist.txt, I changed the interpreter line : set(python_version "3.5.2" CACHE STRING "Specify which Python version to use"). And It worked!

**Comment by wujun** [comment]
Great solution!@H-adorable

**Comment by xnming** [comment]
I am building caffe under Ubuntu 16.04. The solution for me is to change `boost_python3' to `boost_python-py35'.

**Comment by zwx19961130** [comment]
Thank you. This has solved my question.

**Comment by minhaj3** [comment]
I am building caffe in Ubuntu 16.04. For me changing boost_python3 to boost_python-py35 worked. "boost_python3-py35" did not work for me.

**Comment by JFishLover** [comment]
thanks @minhaj3

**Comment by tailongnguyen** [comment]
For those who tried all methods mentioned above and still got the error, check if you have already install libboost-all-dev by running: `sudo apt-get install -y --no-install-recommends libboost-all-devl`.

**Comment by rsingh2083** [comment]
Ive got multiple python versions using pyenv (3.8 and 3.7).
I started the build on python3.7 and since on my system i had boost_python38 hence in the makefile i edited to look for boost_python38 instead of boost_python37
`PYTHON_LIBRARIES := boost_python38 python3.7m`
I did that because` sudo apt-get install -y --no-install-recommends libboost-all-dev` says `requirement already satisfied`.

But now when I do `make -j4` Im getting this error :- 
```

CXX/LD -o .build_release/tools/extract_features.bin
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/9/../../../arm-linux-gnueabihf/libboost_python38.so: undefined reference to `_Py_tracemalloc_config'
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/9/../../../arm-linux-gnueabihf/libboost_python38.so: undefined reference to `_PyTraceMalloc_NewReference'
collect2: error: ld returned 1 exit status
make: *** [Makefile:630: .build_release/tools/get_image_size.bin] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/9/../../../arm-linux-gnueabihf/libboost_python38.so: undefined reference to `_Py_tracemalloc_config'
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/9/../../../arm-linux-gnueabihf/libboost_python38.so: undefined reference to `_PyTraceMalloc_NewReference'
collect2: error: ld returned 1 exit status
make: *** [Makefile:630: .build_release/tools/convert_imageset.bin] Error 1
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/9/../../../arm-linux-gnueabihf/libboost_python38.so: undefined reference to `_Py_tracemalloc_config'
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/9/../../../arm-linux-gnueabihf/libboost_python38.so: undefined reference to `_PyTraceMalloc_NewReference'
collect2: error: ld returned 1 exit status
make: *** [Makefile:630: .build_release/tools/convert_annoset.bin] Error 1
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/9/../../../arm-linux-gnueabihf/libboost_python38.so: undefined reference to `_Py_tracemalloc_config'
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/9/../../../arm-linux-gnueabihf/libboost_python38.so: undefined reference to `_PyTraceMalloc_NewReference'
collect2: error: ld returned 1 exit status
make: *** [Makefile:630: .build_release/tools/extract_features.bin] Error 1
```

**Comment by amoazeni75** [comment]
I wanted to build Caffe and faced the same issue. Unfortunately, none of the answers work in my case. I checked the location of lboost_python by the following command:
<br>
<code> find /usr/lib -name libboost_python-py </code>

I found the lboost_python libraries and here are some of them:
<ul>
<li>libboost_python37.a</li>
<li>libboost_python37-mt.a</li>
<li>libboost_python37-mt.so</li>
<li>libboost_python37-mt.so.1.68.0</li>
</ul>

Then in the **Makefile.config** file I changed the following line: <br>
PYTHON_LIBRARIES := **boost_python** python3.7m   <br>to <br>
PYTHON_LIBRARIES := **boost_python37-mt** python3.7m

**Comment by kivoimusa** [comment]
Thank you so much for this! you are adorable love for everyone. God bless you

**Comment by JFishLover** [comment]
您好！信件已收到
