### ISSUE TITLE
build error "undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)' " 

### ISSUE THREAD

**Issue by youngwanLEE** [BVLC/caffe#4973]
### system configuration
Operating system: Ubuntu 14.04
GPUs : NVIDIA GTX 1080 
Compiler: gcc 5.4
CUDA version: CUDA 8.0 
CUDNN version : cuDNN v5.1

### Problem
Whenever I compile caffe on 3 different PCs, this error always occur. 

I saw other issues which are solved by gcc 4.8 version.

So, When I tried to compile with gcc 4.8, json parser problem occured. Then I changed gcc version to gcc-5.0 version and solved the problem.

```
CXX/LD -o .build_release/tools/convert_imageset.bin
CXX/LD -o .build_release/tools/convert_annoset.bin
CXX/LD -o .build_release/tools/extract_features.bin
CXX/LD -o .build_release/examples/siamese/convert_mnist_siamese_data.bin
CXX/LD -o .build_release/examples/cpp_classification/classification.bin
CXX/LD -o .build_release/examples/ssd/ssd_detect.bin
CXX/LD -o .build_release/examples/cifar10/convert_cifar_data.bin
CXX/LD -o .build_release/examples/mnist/convert_mnist_data.bin
.build_release/tools/convert_imageset.o: In function `main':
convert_imageset.cpp:(.text.startup+0x16b6): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
convert_imageset.cpp:(.text.startup+0x19ae): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/convert_imageset.bin] Error 1
```

Are there people who solve the problems?

Thanks

**Comment by kezewang** [comment]
When using GCC 5.4.1. Please check the GLIBCXX version via strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX

libstdc++.so.6 should be linked to libstdc++.so.6.22 or above

**Comment by Coderx7** [comment]
@kezewang : I'm having the same exact thing, how exactly should I fix this? 
I used `CUSTOM_CXX := /usr/bin/g++-5` in the makefile.config but I have no idea how to do what you said there (I'm a newbie to linux!)

**Comment by kezewang** [comment]
I have solved the problem by using the newest libstdc++.so.6.0.22.
Please check the postfix of your libstdc++.so.6 verison.

**Comment by Coderx7** [comment]
Thanks but I'm lost here! what does 
`Please check the postfix of your libstdc++.so.6 verison.`
mean? I have` libstdc++.so.6.0.22` in `/usr/lib/x86_64-linux-gnu/` so what else should I do?

**Comment by kezewang** [comment]
Try input this into terminal:
locate libstdc++.so.6 (Note that there may be another version of
libstdc++.so.6 in other folders. Please rename them as
libstdc++.so.6_notused )
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH

**Comment by Coderx7** [comment]
This is what I got: 
```
hossein@hossein-pc:/media/hossein/tmpstore/caffe-ssd$ locate libstdc++.so.6
/home/hossein/anaconda2/lib/libstdc++.so.6
/home/hossein/anaconda2/lib/libstdc++.so.6.0.19
/home/hossein/anaconda2/pkgs/libgcc-4.8.5-2/lib/libstdc++.so.6
/home/hossein/anaconda2/pkgs/libgcc-4.8.5-2/lib/libstdc++.so.6.0.19
/usr/lib/i386-linux-gnu/libstdc++.so.6
/usr/lib/i386-linux-gnu/libstdc++.so.6.0.22
/usr/lib/x86_64-linux-gnu/libstdc++.so.6
/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
/usr/share/gdb/auto-load/usr/lib/i386-linux-gnu/libstdc++.so.6.0.22-gdb.py
/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22-gdb.py
```
and renamed all libstdc++.so.6 and libstdc++.so.6.19 to libstdc++.so.6_ and libstdc++.so.6.19_  respectively . 
would not any thing weird happen to me for doing this? especially since I'm using anaconda?

**Comment by Coderx7** [comment]
@kezewang : Thanks alot man, its solved :)

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by SunnyWay** [comment]
`conda install libgcc` works for me.
